#!/usr/bin/env python3
"""skills registry builder.

Structure:
  skills/             -> official skills maintained in this repo (from SKILL.md frontmatter)
  external/*.json     -> external skill index, one JSON file per skill
  registry.json       -> merged big registry (auto-generated by CI)

Unified skill schema (every entry in registry.json):
  name, desc, author, icon-link, skill-single-link, repo
"""
import os
import json
import re
import sys

REPO_URL = "https://github.com/PurrPod/skills"
REGISTRY_FILE = "registry.json"
README_FILE = "README.md"
SKILLS_DIR = "skills"
EXTERNAL_DIR = "external"

REQUIRED_EXTERNAL_FIELDS = ["name", "desc", "author", "icon-link", "skill-single-link", "repo"]


def parse_skill_md(filepath):
    """Extract YAML frontmatter (flat key: value) from SKILL.md."""
    meta = {}
    if not os.path.exists(filepath):
        return meta

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    match = re.search(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if match:
        for line in match.group(1).split("\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                meta[k.strip()] = v.strip().strip("\"'")
    return meta


def load_official_skills():
    """Scan skills/ and build entries from SKILL.md frontmatter."""
    skills = {}
    if not os.path.exists(SKILLS_DIR):
        return skills

    for item in sorted(os.listdir(SKILLS_DIR)):
        skill_dir = os.path.join(SKILLS_DIR, item)
        if not os.path.isdir(skill_dir) or item.startswith("."):
            continue

        meta = parse_skill_md(os.path.join(skill_dir, "SKILL.md"))

        skill_name = meta.get("name", "").strip()
        if not skill_name:
            print(f"❌ 校验失败: [{skill_dir}/SKILL.md] 缺失 'name' 字段！")
            sys.exit(1)
        if skill_name != item:
            print(f"❌ 校验失败: 目录 [{skill_dir}] 与其内部 SKILL.md 的 name 字段 ('{skill_name}') 不一致！")
            print(f"💡 修复建议: 将 SKILL.md 中的 name 修改为 '{item}'，或重命名文件夹。")
            sys.exit(1)

        skills[item] = {
            "name": skill_name,
            "desc": meta.get("description", "暂无描述"),
            "author": "PurrPod",
            "icon-link": "",
            "skill-single-link": f"{REPO_URL}/tree/main/{SKILLS_DIR}/{item}",
            "repo": REPO_URL,
        }
    return skills


def load_external_skills():
    """Scan external/*.json, one file per external skill, with strict validation."""
    skills = {}
    if not os.path.exists(EXTERNAL_DIR):
        return skills

    for item in sorted(os.listdir(EXTERNAL_DIR)):
        if not item.endswith(".json"):
            continue
        filepath = os.path.join(EXTERNAL_DIR, item)
        file_stem = item[: -len(".json")]

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                entry = json.load(f)
        except Exception as e:
            print(f"❌ 校验失败: [{filepath}] JSON 解析失败: {e}")
            sys.exit(1)

        if not isinstance(entry, dict):
            print(f"❌ 校验失败: [{filepath}] 顶层必须是 JSON 对象！")
            sys.exit(1)

        missing = [
            f for f in REQUIRED_EXTERNAL_FIELDS
            if not isinstance(entry.get(f), str) or not entry[f].strip()
        ]
        if missing:
            print(f"❌ 校验失败: [{filepath}] 缺失或为空字段: {', '.join(missing)}")
            print(f"💡 必须包含全部字段: {', '.join(REQUIRED_EXTERNAL_FIELDS)}")
            sys.exit(1)

        skill_name = entry["name"].strip()
        if skill_name != file_stem:
            print(f"❌ 校验失败: [{filepath}] 文件名 ('{file_stem}') 与其 name 字段 ('{skill_name}') 不一致！")
            print(f"💡 修复建议: 将文件重命名为 '{skill_name}.json'，或修改 name 字段。")
            sys.exit(1)

        skills[skill_name] = {f: entry[f].strip() if isinstance(entry[f], str) else entry[f] for f in REQUIRED_EXTERNAL_FIELDS}
    return skills


def generate_markdown_table(skills_dict):
    """Render README markdown table for a set of skills."""
    lines = [
        "| 技能名 (Install ID) | 描述 | 作者 | 仓库 |",
        "| :--- | :--- | :--- | :--- |",
    ]

    if not skills_dict:
        lines.append("| *(虚位以待)* | 期待收录更多技能！ | - | - |")
        return "\n".join(lines) + "\n"

    for short_id, info in sorted(skills_dict.items()):
        desc = info.get("desc", "-")
        author = info.get("author", "-")
        repo = info.get("repo", "#")
        lines.append(f"| **`{short_id}`** | {desc} | {author} | [链接]({repo}) |")

    return "\n".join(lines) + "\n"


def update_readme(official_skills, external_skills):
    """Rewrite the table sections inside README placeholders."""
    if not os.path.exists(README_FILE):
        return

    with open(README_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    for tag, table in [
        ("OFFICIAL", generate_markdown_table(official_skills)),
        ("EXTERNAL", generate_markdown_table(external_skills)),
    ]:
        content = re.sub(
            rf"(\n<!-- BEGIN_{tag}_TABLE -->).*?(\n<!-- END_{tag}_TABLE -->)",
            lambda m: f"{m.group(1)}\n{table}{m.group(2)}",
            content,
            flags=re.DOTALL,
        )

    with open(README_FILE, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    print("[*] 正在扫描 skills/ 目录...")
    official_skills = load_official_skills()

    print("[*] 正在扫描 external/ 目录...")
    external_skills = load_external_skills()

    all_skills = {**official_skills, **external_skills}

    registry = {
        "version": "2.0",
        "repository": REPO_URL,
        "skills": all_skills,
    }

    print("[*] 正在生成 registry.json...")
    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)

    print("[*] 正在更新 README.md...")
    update_readme(official_skills, external_skills)

    print(f"[+] 构建完成！共收录 {len(all_skills)} 个技能 (official: {len(official_skills)}, external: {len(external_skills)})")


if __name__ == "__main__":
    main()
